export interface PlaylistInfo {
  id: string;
  title: string;
  description: string;
  channelTitle: string;
  videoCount: number;
}

export interface VideoInfo {
  id: string;
  title: string;
  description: string;
  channelTitle: string;
  publishedAt: string;
  duration: string; // ISO 8601 duration (PT15M30S)
  durationSeconds: number;
  thumbnailUrl: string;
  url: string;
}

export type CaptionTrackKind = 'standard' | 'ASR' | 'forced';

export interface CaptionInfo {
  id: string;
  videoId: string;
  language: string;
  languageCode: string;
  trackKind: CaptionTrackKind;
  isAutoGenerated: boolean;
}

export interface CaptionResult {
  available: boolean;
  isManual: boolean;
  caption: CaptionInfo | null;
  text: string | null;
}
